### ISSUE TITLE
Error on examples

### ISSUE THREAD

**Issue by indro** [jorgebastida/django-dajaxice#1]
JSON is not defined
http://dajaxproject.com/dajaxice/dajaxice.core.js
Line 52

**Comment by jorgebastida** [comment]
SO and Browser
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.14) Gecko/2009091010 Iceweasel/3.0.14 (Debian-3.0.14-1)

**Comment by jorgebastida** [comment]
I'm working to solve this problem.
Googling about "JSON is not defined" results that some old versions of Firefox hasn't JSON native implementation.

To solve this problem the best approach seems to be include json2.js from json.org

In the next release of  django-dajaxice will include that code to (in case of necessary) implement that JSON object.

The first tests works great.

**Comment by jorgebastida** [comment]
Before some testing, it works great. XmlHttpRequest and json2.js are now included inside dajaxice.
