### ISSUE TITLE
Please remove the setuptools import try

### ISSUE THREAD

**Issue by angelabad** [jorgebastida/django-dajaxice#10]
Hi Jorge, Im again :-D Please remove the try for setuptools in setup.py. For this package with standard python distutils is enough, Remove unnecesary deps, less depends, less problems.

What shit of bug tracker without file upload option :-D

I attach the debian package applied patch:

--- a/setup.py
+++ b/setup.py
@@ -1,7 +1,4 @@
-try:
-    from setuptools import setup
  -except:
-    from distutils.core import setup
  +from distutils.core import setup
  
  setup(
     name = "django-dajaxice",

Thanks for your work!

Best Regards,

**Comment by angelabad** [comment]
http://svn.debian.org/viewsvn/python-modules/packages/dajaxice/trunk/debian/patches/remove_setuptools?revision=12477&view=markup

**Comment by jorgebastida** [comment]
Fixed in http://github.com/jorgebastida/django-dajaxice/commit/335a7b06d5c08911b9cf40ad48ce2b777f0c38bb
