### ISSUE TITLE
Error - Uncaught SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by nawarkhede** [jorgebastida/django-dajaxice#108]
I am using django version 1.4.5 , I am getting this error.

Uncaught SyntaxError: Unexpected token % dajaxice.core.js:1
Uncaught ReferenceError: Dajaxice is not defined

**Comment by ghost** [comment]
Make sure your urls.py is configured properly.

**Comment by wintvelt** [comment]
I am having the same issue. Included the following lines in urls.py as the instructions say:

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

```
url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
```

But still get the same errors.

**Comment by ghost** [comment]
I had a hell of time getting it set up originally. Then, of course, when I finally got it working, I couldn't tell what I had changed to make it work. I guess all I can say is:
1. Make sure the url.py is configured properly:

``` python
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
    dajaxice_autodiscover()
    urlpatterns = patterns("",
         url("^$", direct_to_template, {"template": "index.html"}, name="home"),
         )
```
1. Make sure you're loading dajaxice in the tempate tags:

``` python
    {% load dajaxice_templatetags %}
    <html>
    <head>
    {% dajaxice_js_import %}
    </head>
    </html>
```
1. Make sure the proper template loaders, processors, and static file finder are installed in settings.py:

``` python
    TEMPLATE_LOADERS = (
         'django.template.loaders.filesystem.Loader',
         'django.template.loaders.app_directories.Loader',
         'django.template.loaders.eggs.Loader', # !!!!!!!
         )
    TEMPLATE_CONTEXT_PROCESSORS = (
         'django.contrib.auth.context_processors.auth',
         'django.core.context_processors.debug',
         'django.core.context_processors.i18n',
         'django.core.context_processors.media',
         'django.core.context_processors.static',
         'django.core.context_processors.request',
         'django.contrib.messages.context_processors.messages' # !!!!!!!!!!!
         )
    STATICFILES_FINDERS = (
         'django.contrib.staticfiles.finders.FileSystemFinder',
         'django.contrib.staticfiles.finders.AppDirectoriesFinder',
         'dajaxice.finders.DajaxiceFinder', # !!!!!!!!!!!!!!!!!!!!!!!!!
         )
```

Apologies if this is just a rehash of the documentations for you. This unexpected token you're seeing is from the template used to generate the dajaxice.core.js, meaning that django is just serving up the template as the static file, not the generated js with your ajax functions.

**Comment by wintvelt** [comment]
Thank for the info. When I add the
'django.template.loaders.eggs.Loader',
The app engine (which is what I am using it on) gives me an error message in the log file.
So I guess I need to figure out why the eggs.Loader is rejected..
