### ISSUE TITLE
Exception when adding single ajax method only

### ISSUE THREAD

**Issue by myisis** [jorgebastida/django-dajaxice#12]
This error occurs when stripping down the original 'simple' example. Remove all but 1 of the methods from DAJAXICE_FUNCTIONS and try to load dajaxice.core.js. This is the stacktrace, I obtained. It seems like dajaxice assumes that there's more than 1 method specified...

Environment:

Request Method: GET
Request URL: http://localhost:1234/dajaxice/dajaxice.core.js
Django Version: 1.1.1
Python Version: 2.6.5
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'dajaxice',
 'simple']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware')

Traceback:
File "/usr/local/lib/python2.6/dist-packages/Django-1.1.1-py2.6.egg/django/core/handlers/base.py" in get_response
1.                 response = callback(request, _callback_args, *_callback_kwargs)
   File "/usr/local/lib/python2.6/dist-packages/Django-1.1.1-py2.6.egg/django/views/decorators/cache.py" in _cache_controlled
2.             response = viewfunc(request, _args, *_kw)
   File "/usr/local/lib/python2.6/dist-packages/dajaxice/views.py" in js_core
3.     data = {'dajaxice_js_functions':DajaxiceRequest.get_js_functions(),
   File "/usr/local/lib/python2.6/dist-packages/dajaxice/core/DajaxiceRequest.py" in get_js_functions
4.                     data[module].append(function[2])

Exception Type: IndexError at /dajaxice/dajaxice.core.js
Exception Value: list index out of range

**Comment by readevalprint** [comment]
you need a comma like so:

```
DAJAXICE_FUNCTIONS = (
  'sfdsfsdfsd.sdfsdf',
)
```

**Comment by jorgebastida** [comment]
Thanks coconutrandom
