### ISSUE TITLE
Forked and maintained django-dajaxice

### ISSUE THREAD

**Issue by difanz** [jorgebastida/django-dajaxice#132]
Well, this is not an issue, rather providing an approach for developers using django 1.6 and dajaxice project.

I forked this project, the repository resides here:

https://github.com/ifanrx/django-dajaxice

I promise to maintain this package, patch it from time to time to catch up with Django changes, optimize code, add new functionalities as well as merging from upstreams (if any).

To get started, use:

pip install django-dajaxice-ng

**Comment by jorgebastida** [comment]
I've just released `django-dajaxice 0.6`, now supporting `django 1.6`.
This project will be maintained until `django 1.8` is released in order to not break existing projects using `django-dajaxice`.

https://github.com/jorgebastida/django-dajaxice#should-i-use-django-dajaxice
