### ISSUE TITLE
Proper way to get a callback into a function of a object

### ISSUE THREAD

**Issue by amccool** [jorgebastida/django-dajaxice#14]
From within a js object, I need to have my callback return into the same object making the call.

neither inlining the callback function nor, making a passing a Ext.createCallback seems to work

help?

**Comment by jorgebastida** [comment]
If you know your object name you can use something like "myObject.callback_function" as callback. Dajaxice will execute .... myObject.callback_function(data).

It should work.
Cheers

**Comment by amccool** [comment]
if I could pass a function reference rather than a string for the function, things would work much easier.

basically replace the 'eval' with execution of the passed func reference.

**Comment by amccool** [comment]
accidentally closed this

**Comment by jorgebastida** [comment]
Can you share a workaround to solve this issue ?

**Comment by amccool** [comment]
let me dig thru the the js code generator, and try a few things

**Comment by amccool** [comment]
added a check in DajaxiceRequest.py for callback existance (used 'None' if nothing passed)
modified dajaxice.core.js to eval responsetext then directly execute passed callback js func.

I'll add an ExtJS generated callback func test tonight......all in all I'm not seeing any problems

**Comment by amccool** [comment]
I have a working solution.   Whats the best way for me to submit my changes?

**Comment by jorgebastida** [comment]
If you want, branch dajaxice in github and push the changes, then I can pull the diff.

**Comment by Strav** [comment]
It would indeed be very nice if the callback could be specified as this.my_method(), directly referring to the current object's local scope. I'll be pulling from amccool's repo for now, in hope to see this change merged and documented soon :)

Thanks the fix!

**Comment by jorgebastida** [comment]
In the last HEAD version callbacks can be functions and not strings. Old string based callbacks are still supported but will be deprecated soon.
