### ISSUE TITLE
'+' char stripped from strings on hash tables

### ISSUE THREAD

**Issue by flegoff** [jorgebastida/django-dajaxice#16]
It seems that a string containing a '+' chars in the javascript object on the client side will see its '+' replaced with ' ' (space) on the server side.

For exemple, on the client side :

```
resp = { 'test': 'aabb++--==!!' }

Dajaxice.myproject.myapp.my_func('Dajax.process',
    { 'response' : resp } );
```

When executed, this code gives in the server console :

```
2010-06-25 11:30:56,838 DEBUG Function hcloud.vitale.ajax.hc_process_genererFacture is callable
2010-06-25 11:30:56,839 DEBUG callback Dajax.process
2010-06-25 11:30:56,839 DEBUG argv {' response': {'test': u'aabb  --==!!' } }
```

We can see that something is missing in the 'test' field...

(The results have been edited for clarity).

**Comment by flegoff** [comment]
I looked at the HTTP request with wireshark : everything is correctly received on the server side.

```
(...) %22test%22%3A%22aabb++--(...)
```

**Comment by flegoff** [comment]
The string returned by self.request.POST.get('argv') (DajaxiceRequest.py:194) is, indeed, stripped. I placed a log.debug() below and this is what I get :

```
DEBUG argv(0): {"response":{"test": "aabb  --==!!"}}
```

**Comment by flegoff** [comment]
It seems that escape() encodes everything buts +. I found some documentation here : http://www.ibm.com/developerworks/web/library/wa-aj-jsf1.html (see Getting and encoding the form data).

I'm going to push a fix to my fork repo.

**Comment by flegoff** [comment]
Fixed : http://github.com/madflo/django-dajaxice/commit/6df00b24fe65393f37b7992f2d62b39f62b41fd5

**Comment by jorgebastida** [comment]
Hello madflo,
The workaround on django-dajax issue #11 in my tests fix both bugs (UTF-8 and + characters).
It remplaces escape() with encodeURIComponent()

http://github.com/jorgebastida/django-dajax/issues#issue/11

**Comment by flegoff** [comment]
Sounds good to me !
