### ISSUE TITLE
problem with cyrillic in post

### ISSUE THREAD

**Issue by coolchevy** [jorgebastida/django-dajaxice#17]
Example:
callback=Dajax.process&argv=%7B%22form%22%3A%7B%22description%22%3A%22%u0430%22%2C%22conference%22%3A%227050f7448d9411df982a0026557eb006%22%2C%22image%22%3A%221498f6f58f7148aca69b13ec4e034b89%22%7D%7D

python can't decode %22%3A%22%u0430%22%2C%22 because '%u0430' is not valid unicode string
'%u0430' = cyrilic 'а' symbol

to fix this my patch:

--- /usr/local/src/django/django-dajaxice/dajaxice/core/DajaxiceRequest.py      2010-07-08 14:15:07.246026470 +0300
+++ DajaxiceRequest.py  2010-07-20 11:19:11.010302874 +0300
@@ -59,6 +59,15 @@

 log.info('DAJAXICE_MODERN_IMPORT=%s' % DAJAXICE_MODERN_IMPORT)

+
+from urllib import unquote
+
+def unquote_u(source):
-    result = unquote(source)
-    if '%u' in result:
-        result = result.replace('%u','\u').decode('unicode_escape')
-    return result
  +
  def safe_dict(d):
     """
     Recursively clone json structure with UTF-8 dictionary keys
  @@ -69,7 +78,7 @@
   elif isinstance(d, list):
       return [safe_dict(x) for x in d]
   else:
-        return d
-        return unquote_u(d)

**Comment by jnohlgard** [comment]
replace the escape() with encodeURIComponent() on line 10 in dajaxice/templates/dajaxice/dajaxice.core.js
This was supposed to be fixed in dajaxice 0.1.5 release but it seems it is not. (see: http://github.com/jorgebastida/django-dajax/issues/issue/11#issue/11/comment/271006 )

**Comment by coolchevy** [comment]
thx, it's work.

**Comment by jorgebastida** [comment]
True! Sorry about that. I will reopen the ticket and fix it.  Thanks!
