### ISSUE TITLE
missing some characters

### ISSUE THREAD

**Issue by fengsi** [jorgebastida/django-dajaxice#18]
When you send strings like 'my+stuff' back to dajaxice, the ajax.py will only get 'my stuff' --- the '+' is replaced by ' ' (space)!

But looks like other characters are fine (~!@#$%^&*, etc.).

Not sure if it's a bug or I need to somehow "encode" the string before sending. This issue can be critical as tokens/hashes may often contains '+'. I don't want to send plain text back, of course.

**Comment by fengsi** [comment]
Oh, found solution in previous tickets.

But, seems you forgot to put this bug fix in 0.1.5? I checked the source code but it's still there...
http://github.com/jorgebastida/django-dajax/issues/issue/11#issue/11/comment/301823

**Comment by jorgebastida** [comment]
True! Sorry about that. I will reopen the ticket and fix it.

**Comment by jorgebastida** [comment]
Fixed in http://github.com/jorgebastida/django-dajaxice/commit/d5d941b1e400c1cdf2b75f89cfb68388989e69f5

Thanks!

**Comment by jorgebastida** [comment]
Fixed in 0.1.6

**Comment by jorgebastida** [comment]
Closed in 0.1.7
