### ISSUE TITLE
Wrong path on modules

### ISSUE THREAD

**Issue by iliaskarim** [jorgebastida/django-dajaxice#19]
When modules from two different apps are registered, the paths will be identical in the function call up to the function name itself. See this thread for a better description and my solution:

http://groups.google.com/group/dajaxproject/browse_thread/thread/14f25d5179da4163

**Comment by youen** [comment]
Hi,
i rewrote Dajaxice.py in my branch.
 http://github.com/youen/django-dajaxice

**Comment by jorgebastida** [comment]
Closed in 0.1.7
