### ISSUE TITLE
csrf dajaxice

### ISSUE THREAD

**Issue by ouhouhsami** [jorgebastida/django-dajaxice#2]
i'm working with django version 1.2 alpha 1 SVN-12351
i tried dajaxice, but found a problem with csrf. I get a "403 Forbidden CSRF verification failed. Request aborted."
(is "X-Requested-With: XMLHttpRequest" setn in the http header in dajaxice.core.js ?http://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax)

(thanks for your git)

**Comment by ouhouhsami** [comment]
I add
oXMLHttpRequest.setRequestHeader("X-Requested-With", "XMLHttpRequest") in the dajaxice.core.js file (line 20 )

**Comment by jorgebastida** [comment]
Fixed in HEAD :D
Thanks ouhouhsami
