### ISSUE TITLE
dajaxice 0.1.5 breaks on older version of Django

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajaxice#20]
The new release of dajaxice 0.1.5 breaks on version 1.0.4 of Django because it relies on django.util.importlib which is not available until the 1.1.x versions of Django. The previous version of dajaxice 0.1.4 had code to detect this case.

If the new versions of dajaxice will not be compatible with older versions of Django, it would be helpful if that was mentioned in the documentation or even better dajaxice could check if the version of Django is compatible and display an nice error message.

Unfortunately, I can't easily upgrade my Django version so I will be stuck with the older version of dajaxice if this can't be fixed.

try:
    from importlib import import_module
    DAJAXICE_MODERN_IMPORT = True
except:
    try:
        from django.utils import importlib
        DAJAXICE_MODERN_IMPORT = True
    except:
        DAJAXICE_MODERN_IMPORT = False

**Comment by jorgebastida** [comment]
Thanks for the bug, i'm working to solve it.

**Comment by jorgebastida** [comment]
Check the HEAD version, http://github.com/jorgebastida/django-dajaxice/commit/d5d941b1e400c1cdf2b75f89cfb68388989e69f5

Dajaxice now works with django 1.0.4, importlib isn't required.

**Comment by jorgebastida** [comment]
Fixed in 1.0.6

**Comment by jorgebastida** [comment]
Closed in 0.1.7
