### ISSUE TITLE
Javascript Rendering Issues

### ISSUE THREAD

**Issue by stijlfigurant** [jorgebastida/django-dajaxice#21]
Its probably just me, but I can't get the javascript to render the template tags properly, I just keep getting this error:

invalid property id
http://192.168.1.51/dajaxice/dajaxice.core.js
Line 2

Any clue what im doing wrong? I am using 0.1.5

**Comment by stijlfigurant** [comment]
ok i think it has to do with my nginx/fastcgi setup not serving js correctly

**Comment by stijlfigurant** [comment]
Found that I shoulnd't have configured that Nginx serves my js statically, resolved!

**Comment by jorgebastida** [comment]
Thanks for the feedback :)

**Comment by jorgebastida** [comment]
Closed
