### ISSUE TITLE
Functions called twice

### ISSUE THREAD

**Issue by Strav** [jorgebastida/django-dajaxice#23]
Hi! Firstly, many thanks for this extension; I probably wouldn't have used django if it wasn't for this sweet ajax integration.

As for my issue, perhaps it's a setup problem although I'm far from certain: while their callback is only called once, every python functions called via ajax is raised twice (tested using pdb.set_trace() and a global counter for I wouldn't believe it). 

I've check Dajaxice.py for register_function() and the  _callable property and it seems that at runtime, I'm getting my functions registered twice under my_sub_app.ajax.function and my_main_app.my_sub_app.ajax.my_function(). I've done a dirty patch to fix this behavior but it didn't helped.

And of course, js is only calling those functions once.

Note: I've pulled my version from amccool's repository, perhaps this issue is actually originating from his sources. I'll make a test comparing the your version to his later today.

If you have any insight about this issue, it might save me a lot of time.

Thanks!

**Comment by Strav** [comment]
My bad. I didn't commented the proper line on amccool's modifications

**Comment by jorgebastida** [comment]
Ok, i'll close this.
