### ISSUE TITLE
CSRF verification failed on Django 1.2.5

### ISSUE THREAD

**Issue by aledr** [jorgebastida/django-dajaxice#25]
Hi!

Just updated to 1.2.5 and noticed the 403 error about CSRF verification failed.
Dajaxice-0.1.7

**Comment by aledr** [comment]
Seems that it needs a custom X-CSRFToken header now...
http://docs.djangoproject.com/en/1.2/ref/contrib/csrf/#ajax

Thanks.

**Comment by jorgebastida** [comment]
Fixed in HEAD https://github.com/jorgebastida/django-dajaxice/commit/39a55e6378c389c001e2595371f847519f17d1f3

Ready to be released as 0.1.8

**Comment by flegoff** [comment]
Yay, thank you for the quick fix.

**Comment by gpothier** [comment]
I just downloaded 0.1.8 and I'm getting this error:
"this.get_cookie is not a function" - dajaxice.core.js (line 204)

**Comment by gpothier** [comment]
Note that replacing "this" by "Dajaxice" solves the above issue.

**Comment by jorgebastida** [comment]
Fixed in 0.1.8.1.

Thanks!

**Comment by Viroide** [comment]
Gracias jorge, justo te iba a interceptar mañana para preguntártelo :_D 

Gracias por ser tan rápido, que django te acompañe!
