### ISSUE TITLE
Exception check doesn't work DAJAXICE_DEBUG=True

### ISSUE THREAD

**Issue by arteme** [jorgebastida/django-dajaxice#27]
If DAJAXICE_DEBUG is set to True (which it is by default), the exception detection code:

  if( data == Dajaxice.EXCEPTION ) { ... }

doesn't work since data is now "alert(...)". If the settings is False, there is no information about the exception.

It would be extremely useful if exceptions were provided in an object that is actually checkable for being an exception. Then, the trace-back may be included or omitted based on the DEBUG flag. At this point, the application may choose to call something like alert(data.traceback) or whatever else.

**Comment by jorgebastida** [comment]
Hi arteme,

We are working in a branch to fix that kind of problems with
Dajaxice.EXCEPTIONS.
In that approach we have created a new parameter into the Dajaxice call
where you can specify a
error_callback, so if something goes wrong that function will be called.

Also, Dajaxice have a "default_error_callback" to make this change backward
compatible.

The fork is here:
https://github.com/jorgebastida/django-dajaxice/commit/edd66c9f74a48bb02016949fc717f1499b97c42c

We have discussed that here:
http://groups.google.com/group/dajaxproject/browse_thread/thread/9e69039de8c68ab4

This feature should be released into Dajaxice 0.1.9 in no more than 1 o 2
weeks.

Cheers,
Jorge Bastida.

2011/3/29 arteme <
reply@reply.github.com>

**Comment by jsvh** [comment]
even better instead of doing an alert maybe outputting to the console would be more user friendly.

**Comment by jorgebastida** [comment]
The error_callback branch has been merged into master.
