### ISSUE TITLE
Online examples does not work on Google Chrome  

### ISSUE THREAD

**Issue by montaro** [jorgebastida/django-dajaxice#28]
Dear all,

In my first attempt to explore dajaxice, I tried the online examples on chrome and it did not work, but it worked correctly on firefox.
http://www.dajaxproject.com/dajaxice/
http://www.dajaxproject.com/dajaxice-args/
I get the alert but the text is always "undefined"
Thanks

**Comment by paveltyavin** [comment]
Have the same problem

**Comment by paveltyavin** [comment]
Ok, I found out. The problem was in different settings. As for me, I need to write
onclick="Dajaxice.projectname.appname.function('js');" not just onclick="Dajaxice.appname.function('js');"

**Comment by jorgebastida** [comment]
montaro, can you send us your chrome version an so ?

Thanks

**Comment by montaro** [comment]
I'm terribly sorry, I can not remember what was the version, it might have been 10.x.x
Now I'm using google-chrome v.11.0.696.65 and It works fine.
Thanks,

**Comment by flegoff** [comment]
FYI it's pretty common to have Dajaxice related issues with Google Chrome.

It seems that Chrome is caching .js files pretty aggressively.

In my case, if my ajax.py is broken in an app, this apps disappears from the Dajaxice-generated js file. The usual.

But when I do fix my ajax.py file ; a cache reset is needed in Chrome. It's working flawlessly in Firefox and Safari, once again pointing me to an experimental Chrome caching feature.
