### ISSUE TITLE
optional comment string sent as argument to "register"

### ISSUE THREAD

**Issue by apparator** [jorgebastida/django-dajaxice#29]
Hi,

Thank you for a very useful django extension.
I really enjoy how I can reference the generated dajaxice/dajaxice.core.js file and see available ajax functions. For the way my team works, it would be perfect if I could send a small doc-string with the register function, which would appear as a comment as first line inside the js function, like this:

```
dajaxice_functions.register(bar, "Send size and age, receive list bla bla")
```

And then in dajaxice/dajaxice.core.js:

```
var Dajaxice = {
  foo: {
    bar: function(callback_function, argv){
       /* Send size and age, receive list bla bla */
       Dajaxice.call('foo.bar', callback_function, argv);

},
....    
```

I suppose the comment could be added if DEBUG=True only.

**Comment by jorgebastida** [comment]
Sounds good for me, but what about using the docstring (function.**doc**) as the comment instead adding anther parameter?

**Comment by apparator** [comment]
That would be absolutely great!

**Comment by jorgebastida** [comment]
I've just pushed a proposal https://github.com/jorgebastida/django-dajaxice/commit/2bb714d5c2111a6cebd2040e3551cd11332d6621

Let me now if that is what you are looking for.

Thanks!

**Comment by apparator** [comment]
Perfect! 

Thanks a lot!
