### ISSUE TITLE
Missing csrftoken cookie causes CSRF errors

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajaxice#30]
The csrftoken cookie is only set by Django when a {% csrf_token %} tag is used in a form. Dajaxice needs this cookie to be set to make an ajax request without be blocked by Django's csrf protection. When a new user visits a site they may not initially have this cookie set which means the ajax requests made by Dajaxice fail.

This is easy to reproduce by clearing the cookies for a site and then making an ajax request through Dajaxice. Since the cookie has not been set, the X-CSRFToken header sent by Dajaxice is null and Django will reject the request as a CSRF error.

This issue is documented as Django bug #15354 http://code.djangoproject.com/ticket/15354

My workaround is to force Django to set the cookie on every request with the following MiddleWare:

<pre>
class CsrfFixMiddleware:
    def process_view(self, request, view_func, callback_args, callback_kwargs):
        request.META["CSRF_COOKIE_USED"] = True
        return None
</pre>

**Comment by flegoff** [comment]
Following the commit http://code.djangoproject.com/changeset/16192 ; a new decorator ' ensure_csrf_cookie' has been made available.

**Comment by jorgebastida** [comment]
Thanks for your reply @madflo

**Comment by gerdemb** [comment]
Hmmm... is the decorator the best solution to this problem? Every view that uses dajaxice will need to be decorated. If that is the plan, at least it should be clearly documented. I believe this issue will effect almost everyone who uses dajaxice and is particularly nasty because you are unlikely to see it on any browser used for development as they will already have the cookie. The resulting CSRF error message is also a little cryptic and it took me quite a while to figure out what was going on. I guess what I'm saying is that I think is a nasty issue that will effect a very large percentage of users....

**Comment by jorgebastida** [comment]
Every view that uses dajaxice should be decorated as every template that have a forms should add {% csrf_token %} .

This behaviour should be correctly documented but there isn't to much we can do inside dajaxice to ease this.

Thanks!

**Comment by gerdemb** [comment]
If you modify the code for the dajaxice_js_import template tag like this, Django will automatically include the CSRF cookie for any page that uses {% dajaxice_js_import  %}

``` @register.inclusion_tag('dajaxice/dajaxice_js_import.html',takes_context=True)
def dajaxice_js_import(context):
    context.get('csrf_token', None)
    return { 'DAJAXICE_MEDIA_PREFIX': DajaxiceRequest.get_media_prefix() }
```

**Comment by jorgebastida** [comment]
Interesting, but if you are serving the file statically?

We can modify the templatetag to also handle statically served files...

``` python
@register.inclusion_tag('dajaxice/dajaxice_js_import.html', takes_context=True)
def dajaxice_js_import(context, core_url=None):
    context.get('csrf_token', None)
    if not core_url or DajaxiceRequest.get_debug():
        core_url = '/%s/dajaxice.core.js' % DajaxiceRequest.get_media_prefix()
    return {'core_url': core_url}
```

If there isn't a core_url or we have DAJAXICE_DEBUG = True we will include the dynamic file, else (if there is a core_url and we aren't in debug mode) we will include that core_url.

Cheers

**Comment by jorgebastida** [comment]
Check this commit
https://github.com/jorgebastida/django-dajaxice/commit/3bdf3ea35a44017e00483fbbc9cec50e7aaf1362#L3R48

**Comment by crazyscientist** [comment]
During development I had always a session cookie set, but now I just noticed this issue and am confused:
In the official documentation on version 0.2 you are suggesting one way to get along with CSRF and here you are suggesting another one....
I followed the instructions in the documentation and it did not work; Dajaxice is returning a CSRF 403 view...

**Comment by jorgebastida** [comment]
All this CSRF issues are now fixed in the upcoming django-dajaxice 0.5 version (currently on the development branch).

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice

**Comment by alejo8591** [comment]
Problem

loading your application and try to interact with dajaxice on the "problems" of safari appears:

![Captura de pantalla 2013-01-14 a la s 23 19 08](https://f.cloud.github.com/assets/1151850/66821/e1d7f4ee-5eca-11e2-8cf4-c80d0f002c76.png)

Solution

For those who have this problem are not scared because Dajaxice already have solved this problem, what to do is use the RequestContext dela follows:

django.template from import RequestContext

method or function in the view:

``` python
def view(request):
      context = {'form': form}
      return render_to_response ("registration / register.html", context, , context_instance = RequestContext (request))
```

This solves the problem of csrf_token

![Captura de pantalla 2013-01-14 a la s 23 12 53](https://f.cloud.github.com/assets/1151850/66810/e35f2e46-5ec9-11e2-8ad8-e5da941b3b89.png)
