### ISSUE TITLE
cannot find way to use urls from urlconf

### ISSUE THREAD

**Issue by abhisheksin** [jorgebastida/django-dajaxice#32]
Hello Jorge,

Dajaxice it appears goes arounf django's url conf, is there a way to use 
urls from urlconf

**Comment by jorgebastida** [comment]
Can you share an example or a further explanation?

Thanks!

**Comment by flegoff** [comment]
Dear @abhisheksin : it is possible to build urls from urlconf using the function reverse.

```
from django.core.urlresolvers import reverse

def my_function(request, customer_id):
    dajax = Dajax()
    dajax.redirect(reverse('customers', args=(customer_id, )))
    return dajax.json()
```

**Comment by jorgebastida** [comment]
@abhisheksin is that what your are looking for?
