### ISSUE TITLE
race condition with the 'is_callback_a_function' variable

### ISSUE THREAD

**Issue by chifflier** [jorgebastida/django-dajaxice#33]
Hi,

When two ajax calls are done simultaneously, one with a function as callback and one with string as callback, the result is likely to fail because 'is_callback_a_function' takes the value of the most recent call.

call 1: string as callback -> is_callback_a_function = false
call 2: function as callback -> is_callback_a_function = true
result of call 1: use is_callback_a_function = true, which is wrong

BR,
Pierre

**Comment by jorgebastida** [comment]
Hi chifflier,
I've just pushed a patch to that race condition. is_callback_a_function was a global var and not a local var.

https://github.com/jorgebastida/django-dajaxice/commit/2d8e37d21a785a3e700e50842b48553341cffc25
