### ISSUE TITLE
Calling other methods

### ISSUE THREAD

**Issue by jsvh** [jorgebastida/django-dajaxice#35]
I can't call any other methods in ajax.py

ajax.py

def method1(request):
   pass

def method2(request):
    request.method1()

I've tried calling every iteration

method1()
self.method1()

Not sure how to resolve it.  I can hack it by not reusing the code and just copying it over.  Maybe I am missing something.

Any thoughts?

**Comment by jorgebastida** [comment]
Hi jsvh,
I'm not sure what are you asking for but as far as I can imaging you are trying to reuse the code of a dajaxice function.
There are other ways, this is only one.

def common(request):
    # do some stuff

def method1(request):
    common(request)
    # other stuff

def method2(request):
    common(request)
    # other stuff

Cheers
