### ISSUE TITLE
dajaxice callbacks are called twice if the callback function throws an exception

### ISSUE THREAD

**Issue by dbasden** [jorgebastida/django-dajaxice#36]
Hey there,

I've noticed that if my callbacks are throwing an exception then the callback is being
called again, but this time without the JSON parsed.  Digging through, I found this in
dajaxice_core.js:

```
                try{
                    dajaxice_callback(JSON.parse(this.responseText));
                }
                catch(exception){
                    dajaxice_callback(this.responseText);
                }
```

The try/catch block seems to be to catch failures in JSON parsing, but is also catching
other exceptions from the handler, and then calling the handler again.

Maybe something like:

var response;
try {
   response = JSON.parse(this.responseText));
}
catch (exception) {
  response = this.responseText;
}
dajaxice_callback(response);

**Comment by jorgebastida** [comment]
+1 Fixed

Thanks!!
