### ISSUE TITLE
example question

### ISSUE THREAD

**Issue by semanty** [jorgebastida/django-dajaxice#39]
<input type="text" value="Some text...">

<input type="button" value="Send message to server!" onclick="Dajaxice.examples.dajaxice_args_example(my_callback, {'text':$('text').value})">

 This is your example for arg, No effects for me. The 'text' shall be text?

**Comment by jorgebastida** [comment]
Hi semanty,

I'm not completely sure about what's your problem.

Your code isn' correct. you should add (i.e an id) to the input field an use
it in the "onclick" like this:

<input type="text" value="Some text..." id="my_input_id">

<input type="button" value="Send message to server!"
onclick="Dajaxice.examples.dajaxice_args_example(my_callback, {'text':$('
my_input_id').value})">

Cheers

2011/8/8 semanty <
reply@reply.github.com>
