### ISSUE TITLE
generate_static_dajaxice command doesn't work when using easy_install

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajaxice#4]
It seems that Django cannot recognize new management commands when Python packages are installed as eggs by easy_install. Adding 'zip_safe = False' should solve this problem by preventing easy_install from zipping (or egging) the package allowing Django to recognize the generate_static_dajaxice command. An explanation is here:

http://stackoverflow.com/questions/1145524/how-to-make-easy-install-expand-a-package-into-directories-rather-than-a-single-e

**Comment by jorgebastida** [comment]
Thanks, fixed in HEAD.
