### ISSUE TITLE
No support for non-blank SERVER_ROOT_URL?

### ISSUE THREAD

**Issue by chriscrowe** [jorgebastida/django-dajaxice#41]
I have a non-blank SERVER_ROOT_URL for a particular project, which means URLs for all the views in my project are of the form:
www.mysite.com/project_name/some_view

Instead of:
www.mysite.com/some_view

My configuration is only this way in the production server, not the dev server. Consequently, dajax works great on my dev server but not the production server. It seems the reason for this is because dajaxice uses only DAJAX_MEDIA_PREFIX to generate the paths to the ajax views and doesn't take SERVER_ROOT_URL into account. The result on my production server is that the ajax view urls look like this:
www.mysite.com/dajaxice/myapp.some_view

When they should really look like this:
www.mysite.com/project_name/dajaxice/myapp.some_view

Can you offer some insight here? I've spent hours trying to figure out if I just had it configured incorrectly... I tried changing the DAJAX_MEDIA_PREFIX to something else but it didn't seem to fix the problem since you have multiple dependencies on that prefix in your code...

**Comment by chriscrowe** [comment]
Any updates on this? I'm dying to deploy my ajax code on the production server.

**Comment by nanonyme** [comment]
This sounds like a bug in dajax, not dajaxice.

**Comment by jorgebastida** [comment]
This issue should be fixed now on the upcoming 0.5 version (Currently on the development branch)

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice
