### ISSUE TITLE
TEMPLATE_CONTEXT_PROCESSORS question

### ISSUE THREAD

**Issue by garyrob** [jorgebastida/django-dajaxice#42]
The docs (http://docs.dajaxproject.com/dajaxice/installation.html) say: "Ensure that TEMPLATE_CONTEXT_PROCESSORS has django.core.context_processors.request.:"

I displayed django.conf.settings.TEMPLATE_CONTEXT_PROCESSORS and it did not contain that; apparently it's not in the default.

Is the proper procedure to override TEMPLATE_CONTEXT_PROCESSORS in my project's settings.py? Or should it have been there without my doing that, in which case what was supposed to make that happen?

The docs seem a little unclear on this.

**Comment by jorgebastida** [comment]
Yes garyob, override your settings.py TEMPLATE_CONTEXT_PROCESSORS is the proper procedure::

```
TEMPLATE_CONTEXT_PROCESSORS = ("django.contrib.auth.context_processors.auth",
                               "django.core.context_processors.debug",
                               "django.core.context_processors.i18n",
                               "django.core.context_processors.media",
                               "django.core.context_processors.static",
                               "django.core.context_processors.request",
                               "django.contrib.messages.context_processors.messages")
```
