### ISSUE TITLE
exception in js_core()

### ISSUE THREAD

**Issue by kneufeld** [jorgebastida/django-dajaxice#43]
If kwargs are defined in your urlpatterns, then you get errors in js_core() and dajaxice_request.

Example:
myproject/urls:
...
url(r'^', include('someapp.urls'), {'key':'values'} ),

someapp/urls:
...
url( dajaxice_url, include('dajaxice.urls') ),

FIX:
dajaxice/views.py:
-def dajaxice_request( request, call ):
+def dajaxice_request( request, call, _args, *_kwargs ):

-def js_core( request ):
+def js_core( request, _args, *_kwargs ):

**Comment by jorgebastida** [comment]
The upcoming 0.5 version now use static files so all this views doesn't exists now, and also... all this issues should be fixed now.

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice
