### ISSUE TITLE
Error in example page

### ISSUE THREAD

**Issue by mdgart** [jorgebastida/django-dajaxice#44]
in this page

http://www.dajaxproject.com/dajaxice/

the alert in the js callback should be `alert(data.message);` not `alert('Error');`

**Comment by mnowotka** [comment]
+1

**Comment by jorgebastida** [comment]
I've rewrite the entire project page (It's going to be released soon both live and as an opensource project on github).

Thanks!

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice
