### ISSUE TITLE
Cancelling an AJAX response listener - jqXHR.abort() equivalent 

### ISSUE THREAD

**Issue by eamonnfaherty** [jorgebastida/django-dajaxice#47]
Is there a way of cancelling listeners in a similar fashion to jqXHR.abort()?

**Comment by jorgebastida** [comment]
Fixed in django-dajaxice 0.5. I'll release it soon.
Thanks!

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice
