### ISSUE TITLE
Root of Onclick button

### ISSUE THREAD

**Issue by ghost** [jorgebastida/django-dajaxice#48]
I have a fail in the root of de onclick button... My application is called 'ajax'... and inside I have a views.py

I write:
onclick="Dajaxice.ajax.views(my_callback)">???????

I probe diferent forms but I don´t resolve it...

Thanks.
Greatings

**Comment by nanonyme** [comment]
Don't have app called ajax. https://github.com/jorgebastida/django-dajaxice/blob/master/dajaxice/core/Dajaxice.py#L115 removes .ajax from module path. The module name which contains the views is expected to be called ajax.py.
