### ISSUE TITLE
Problem with Opera Turbo mode

### ISSUE THREAD

**Issue by domarmstrong** [jorgebastida/django-dajaxice#49]
Ive been using Dajaxice for a simple project, this morning I turned on turbo and then had "something goes wrong", spent a while trying to work out what was going on, then turned it off and it worked fine again.

Not a problem for my small project as its personal, but thought its worth knowing.

**Comment by jorgebastida** [comment]
Thank you very much for the report, but can you provide us any kind of feedback about what's the error itself ?
