### ISSUE TITLE
JavaScript created for dajaxice.core.js is incorrect

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajaxice#5]
The JavaScript created in dajaxice.core.js has a trailing comma, which causes a failure in IE6 and Google Closure won't compile it. The IE6 error is “Expected identifier, string, or number”. The Google error is: "JSC_TRAILING_COMMA: Parse error. Trailing comma is not legal in an ECMA-262 object initializer at line 13 character 9"

The problem is the trailing comma after the definition of pickable_semesters.

var Dajaxice = {

```
    escola: {

            copy_atividade: function(callback_function,argv){
                Dajaxice.call('escola.copy_atividade',callback_function,argv);
            },

            pickable_semesters: function(callback_function,argv){
                Dajaxice.call('escola.pickable_semesters',callback_function,argv);
            }, //  This comma should be deleted

    },
```

**Comment by jorgebastida** [comment]
Hello gerdemb,
What version of dajaxice are you using?
As you can see http://github.com/jorgebastida/django-dajaxice/blob/master/dajaxice/templates/dajaxice/dajaxice.core.js#L7 dajaxice checks if that function is the last to avoid including that trailing comma.

Can you share more information about your environment ?
Thanks

**Comment by gerdemb** [comment]
I'm using a slightly older version of Django 1.0.2 but the line:

{% ifnotequal forloop.counter functions|length %},{% endifnotequal %}

doesn't work for me. I checked the values of forloop.counter and functions|length and they are correct, but the if doesn't work correctly. (Maybe you can't compare "filtered" values or something?) Anyway, the following code worked as a replacement and as a bonus is a little cleaner anyway:

{% if not forloop.last %},{% endif %}

**Comment by jorgebastida** [comment]
My crappy implementation works for me, but yours seems better, faster and stronger.
Fixed in HEAD.

Thanks a lot
