### ISSUE TITLE
A problem when calling Dajaxice in html

### ISSUE THREAD

**Issue by Microkiller** [jorgebastida/django-dajaxice#52]
My problem :

When loading a new page, the page will call a Dajaxice function in Django, and dynamically creates a table, buttons or something else. 
Sometimes it takes some time to run the Dajaxice function. If the user press the backwards button during that the period, an error msg will occur.
 I am now trying to avoid this error. One way I figured out till now is to disable all the things on the page while running the Dajaxice. But I can't disable the tool bars of the browser. The error will still happen when the user using the back button of the tool bar. Can anyone provide a better solution? Thank you very much.

**Comment by jorgebastida** [comment]
Have you found a solution?

**Comment by tampo80** [comment]
django is not rending /static/dajaxice/dajaxice.core.js
