### ISSUE TITLE
onclick in examples

### ISSUE THREAD

**Issue by kilbswhitecrow** [jorgebastida/django-dajaxice#55]
The examples give the onclick code in the form of:

onclick="Dajaxice.example.myexample(my_js_callback);"

This failed for me under Firefox 11 (the alert flicked onto the screen, then was immediately removed) and recent Safari (alert appears with the usual "Something goes wrong" message). I was using "" for the href URL.

Changing this to:

onclick="Dajaxice.example.myexample(my_js_callback); return false;"

means the alert appears, displaying data.message correctly, in both browsers.

**Comment by jorgebastida** [comment]
This issue should be fixed in django-dajaxice 0.5

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice

**Comment by kilbswhitecrow** [comment]
Excellent, thanks.
