### ISSUE TITLE
dajaxice cannot be located at samba directory of windows share

### ISSUE THREAD

**Issue by junhuichen** [jorgebastida/django-dajaxice#56]
python setup.py install 
or 
pip install django-dajaxice

in windows, create a share

mount this share to linux

move the newly installed dajaxice to a this mounted directory
(move to other directory does not cause this problem)

in any django project

python manage.py shell

> > > import sys
> > > sys.path.append("<this mounted directory>")
> > > from dajaxice import *
> > > NO PROBLEM
> > > from dajaxice.core import *
> > > ImportError: No module named core

**Comment by jorgebastida** [comment]
I think this issue is not related with django-dajaxice, anyway... why are you doing this?

**Comment by jorgebastida** [comment]
Fixed on 0.5.3
