### ISSUE TITLE
Need help to send parameters to a function in ajax.py

### ISSUE THREAD

**Issue by ada-pineda** [jorgebastida/django-dajaxice#57]
Hello

I've been doing something with dajaxice, very simple, just to see that everything is working fine. Now, I want to do some complicated work but I don't know how to send parameters to the function.

I have an Id, and I need to get some data based on that id so, I need to send it to the function and work around that id and retrieve the data related to the id.

I've tried using Dajaxice.MyApp.myExample(my_js_callback,{'data':this.id}); but it throws an error: TypeError: myexample() got an unexpected keyword argument 'data'.

Can anyone help me? Please is urgent!

**Comment by jorgebastida** [comment]
Your function "myExample" should have two arguments, request and data as you are sending it from javascript.

**Comment by ada-pineda** [comment]
First: Thank you for the answer, Jorge, but it didn't give the answer I really need, so I don't understand why you closed this issue if I didn't say that it was the solution to my problem.

Second: I solved this by putting the keys in the map as arguments in my method. This is, if my map is {''data':'somedata', 'name':'aname'} I must put the same key names as arguments in my method, so it will be: myMethod(request,data,name).

I knew I should have two arguments, one for the request and one for the map. What I didn't know was that they must have the same name as the keys and the arguments must be the same quantity of elements in the map.

Regards.

Ada Pineda.

**Comment by bluecerebudgerigar** [comment]
Thanks Ada-pineda, thats's really helpful information that seems trivial but really very useful that is missing in the documentation.
