### ISSUE TITLE
dajaxice.core.js sent as application/octet-stream

### ISSUE THREAD

**Issue by dekoza** [jorgebastida/django-dajaxice#59]
I'm not sure if this is a bug or feature but Chrome's webmaster tools complains that dajaxice.core.js is sent as application/octet-stream (although it is still interpreted as a Script). It is probably due to change of the way you serve static files as now you render the js from a template.

**Comment by gegenschall** [comment]
I'm having the same issue here. Right now I'm not really sure how to solve this. Any ideas?

In my case, Chrome says: "Resource interpreted as Script but transferred with MIME type application/octet-stream: <url>." but the script is not working, i.e. not interpreted.

**Comment by jorgebastida** [comment]
Hello, 

As far as I know there is not a way to fix this in a proper way (on development).
On production, you should setup your nginx/apache in order to server these static files (i.e js) using the correct mime-type.

Nginx example:

```
types {
    text/html                             html htm shtml;
    text/css                              css;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/x-javascript              js;
    ...
}
```

Hope this helps you
