### ISSUE TITLE
dajaxice.core.js is not correct when using "longer" DAJAXICE_FUNCTIONS - (module.module.function)

### ISSUE THREAD

**Issue by mkramb** [jorgebastida/django-dajaxice#6]
example: 
   DAJAXICE_FUNCTIONS = ('cms.auth.ajax.helloworld',)

**Comment by readevalprint** [comment]
same problems for me

**Comment by jorgebastida** [comment]
I think this Issue #13 is the best approach to solve this problems.
http://github.com/jorgebastida/django-dajaxice/issues#issue/13

**Comment by jorgebastida** [comment]
Follow http://github.com/jorgebastida/django-dajaxice/issues/#issue/13/comment/262062

Thanks!

**Comment by jorgebastida** [comment]
Check the HEAD version, there is a new approach to register dajaxice functions that resolves this issue.
