### ISSUE TITLE
XMLHttpRequest does not pass params when method is set to GET

### ISSUE THREAD

**Issue by eamonnfaherty** [jorgebastida/django-dajaxice#60]
I have changed my decorator to look like the following:
feeds/ajax.py

``` python
@dajaxice_register(method='GET')
def profile(request, id):
...
```

I have collected my static so my JS looks like:
dajaxice.core.js

``` javascript
function (callback_function, argv, custom_settings){
        Dajaxice.call('feeds.profile', 'GET', callback_function, argv, custom_settings);
}
```

versions

``` bash
$ pip freeze | grep dajax
django-dajax==0.9.2
django-dajaxice==0.5.1
```

The problem seems to be the included XMLHttpRequest does not pass on the argv values when the method is set to GET.

**Comment by eamonnfaherty** [comment]
https://github.com/jorgebastida/django-dajaxice/blob/master/dajaxice/views.py looks like it will work.  It is just the XMLHttpRequest that is causing the failure.

**Comment by eamonnfaherty** [comment]
according to http://www.w3schools.com/ajax/ajax_xmlhttprequest_send.asp the data param is only supported on POST methods. This means that there is currently no pass data on a GET.

**Comment by eamonnfaherty** [comment]
forked so I can add csrf exclude. This means I am still POSTing the data but at least I can cache it now

**Comment by jorgebastida** [comment]
Hello @eamonnfaherty 
Thank you very much about your suggestion. What about sending the args as part of the url if the request is GET?

https://github.com/jorgebastida/django-dajaxice/commit/f878f5e845bee2e511c70e7fd87992fa21f7569e

I've push this changes to develop, and I'll release them soon as 0.5.2.

Thanks!

**Comment by eamonnfaherty** [comment]
Yeah, that would work well!  

I did look into making that change and it was too much for me to take on at the moment. It would be a good addition.  When I get some time I will look at it -- if you (or anybody else) hasn't looked at it in the meantime.
