### ISSUE TITLE
Incorrect DajaxiceStorage.files path on Windows systems

### ISSUE THREAD

**Issue by vxr** [jorgebastida/django-dajaxice#65]
I recognize this may be low priority as you probably have very few users on Windows (I am only using it as a dev environment for early stage prototyping).

The DajaxiceStorage.files dictionary contains a hardcoded forward slash, but the path for the virtual file when looked up on Windows uses backslashes.

I've gotten around this by monkeypatching the following:

from dajaxice.finders import DajaxiceStorage
DajaxiceStorage.files.update({'dajaxice\dajaxice.core.js': 'dajaxice_core_js'})

**Comment by jorgebastida** [comment]
Fixed on 0.5.3
