### ISSUE TITLE
links wrong on dajaxproject.com

### ISSUE THREAD

**Issue by karansag** [jorgebastida/django-dajaxice#67]
Not really a technical issue with the library itself, but I thought I should let you know that your links on dajaxproject.com are somewhat broken.

In particular, some links on the dajax detail page (the one with dajax examples) point to dajaxice sites. The documentation and github links are actually pointing to dajaxice, and so is the navigation link (home/dajax/...) at the top of that page.

**Comment by jorgebastida** [comment]
I've fix this links, thanks!
