### ISSUE TITLE
Can't work in django 1.5.x

### ISSUE THREAD

**Issue by bearmingo** [jorgebastida/django-dajaxice#72]
I installed django 1.5.1a. every ajax request respone "takes exactly 2 arguments (1 given)"

**Comment by maiksprenger** [comment]
I ran across the same problem. There's a pull request to fix it in https://github.com/jorgebastida/django-dajaxice/pull/78

**Comment by jorgebastida** [comment]
Fixed on #77  I'll release this changes as 0.5.5 soon
