### ISSUE TITLE
Syntax error in dajaxice.core.js

### ISSUE THREAD

**Issue by letoosh** [jorgebastida/django-dajaxice#74]
After upgrading dajaxice I'm getting this error:

Uncaught SyntaxError: Unexpected token , :8000/static/dajaxice/dajaxice.core.js:58

Which seems to this line in the js file:

``` javascript
57: // ... previous module
58: y,y
59: // ... next module
```

I think it's the change from 2 days ago:

https://github.com/jorgebastida/django-dajaxice/commit/264805ebbaf2c5ec77fee2ba1c9cd81b41d8f91e#L0R8

Am I missing something?

**Comment by jorgebastida** [comment]
Just released django-dajaxice 0.5.4 fixing this typo.

Thanks!
