### ISSUE TITLE
Syntax error in dajaxice.core.js

### ISSUE THREAD

**Issue by antonagestam** [jorgebastida/django-dajaxice#77]
I get a syntax error ("Uncaught SyntaxError: Unexpected token , ") in my dajaxice.core.js file. For some reason two commas are being generated in between my two modules, where there should be only one.

Here's a gist of the broken dajaxice.core.js file: https://gist.github.com/4266831

**Comment by JirkaV** [comment]
Confirmed, have the same problem. Looks like it was introduced in 264805ebbaf2c5ec77fee2ba1c9cd81b41d8f91e

**Comment by antonagestam** [comment]
This fix works for me https://github.com/antonagestam/django-dajaxice/commit/b0569bca1457ee2c4f289548c77e0c1335b72ce8

**Comment by JirkaV** [comment]
+1 on that fix, apologies for not posting it myself

**Comment by jorgebastida** [comment]
Hello guys,

Merged and released as 0.5.4.1

Thank you very much,
Jorge.

2012/12/19 Jirka Vejrazka notifications@github.com
