### ISSUE TITLE
Decorator (legacy) returns a tuple instead of a function

### ISSUE THREAD

**Issue by JirkaV** [jorgebastida/django-dajaxice#81]
When using legacy @dajaxice_register  decorator (with no parameters), the decorated function becomes a tuple (with only one element, the function itself). This seems to be caused by this code in the dajaxice_register:

```
    if len(dargs) and not dkwargs:
        dajaxice_functions.register(*dargs)
        return dargs
```

Adding an explicit (method='POST') to the decorator fixes the issue.

**Comment by jorgebastida** [comment]
Thank you very much,
I've fixed the issue and I'll relase this changes as dajaxice 0.5.5 soon.
