### ISSUE TITLE
Documentation: dajax.process for request

### ISSUE THREAD

**Issue by alejo8591** [jorgebastida/django-dajaxice#83]
indicate lack of documentation you need to add:
src="/static/dajax/jquery.dajax.core.js"
in the case of jQuery, or the library needed to work with dajax, that but get the error to: Dajax.process

Uncaught ReferenceError: 127.0.0.1:16 Dajax is not defined
(anonymous function) 127.0.0.1:16
jquery-1.7.2.min.js f.event.dispatch: 3
h.handle.i

I discovered this thanks to the chrome debug function it is not:
Dajax.process

**Comment by jorgebastida** [comment]
Fixed, thanks!
