### ISSUE TITLE
Quick fix: Missing commas for multiple ajax modules

### ISSUE THREAD

**Issue by kkansky** [jorgebastida/django-dajaxice#85]
Lines 7-8 of dajaxice.core.js should be changed to:

{% for name, module in dajaxice_config.modules.submodules.items %}
{% include "dajaxice/dajaxice_module_loop.js" %},
{% endfor %}

The current lines are wrong:

{% for name, module in dajaxice_config.modules.submodules.items %}
{% include "dajaxice/dajaxice_module_loop.js" %}{% endfor %}{% if dajaxice_config.modules.submodules %},{% endif %}

**Comment by tcx9871** [comment]
+1

**Comment by uzihs** [comment]
+1

**Comment by jorgebastida** [comment]
This changes are now on `develop` I'll release these as dajaxice 0.5.5 soon
