### ISSUE TITLE
Example is not working: Uncaught syntax error: Unexpected identifier at line number 37.

### ISSUE THREAD

**Issue by dipankar08** [jorgebastida/django-dajaxice#86]
![Error](https://f.cloud.github.com/assets/1300779/32980/30bfbbb8-5058-11e2-9db3-3b9a1dacb428.JPG)
Problem :
I was just testing Examples in Djangi-dajaxice , and found it is not working. I was getting an JS error : Uncaught syntax error: Unexpected identifier at line number 37.

After some investigation, I found that  a comma was missing before "more" objects. At line number 17 of generated Dajaxice.core.js .

**Comment by punkle** [comment]
I am also having the same issue. Reverting the following change https://github.com/jorgebastida/django-dajaxice/commit/b0569bca1457ee2c4f289548c77e0c1335b72ce8 as suggested in a comment works for my situation.

**Comment by maiksprenger** [comment]
Same issue here. I've asked antonagestam via email to elaborate here on the 'double comma bug' that this commit tries to fix.

**Comment by antonagestam** [comment]
@maikhoepfel This is the issue I tried to fix: https://github.com/jorgebastida/django-dajaxice/issues/77#issuecomment-11497738

**Comment by ghost** [comment]
I don't understand why for somebody work the fix #77 and for others no. I'm in the second group. :)
I'm using Dajax. Could be the reason?

**Comment by antonagestam** [comment]
It's probably based on how your project's modules are arranged. I haven't
had the time to dig deeper into a better fix yet.

2013/1/9 esevece notifications@github.com

> I don't understand why for somebody work the fix #77https://github.com/jorgebastida/django-dajaxice/issues/77and for others no. I'm in the second group. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jorgebastida/django-dajaxice/issues/86#issuecomment-12031054.

## 

_Anton Agestam_
anton@fundedbyme.com
+46 708 512 938
@agestam http://twitter.com/agestam
fundedbyme.com
antonagestam.se

**Comment by ghost** [comment]
Ok. Don't worry.
I've commented because I thought that Dajax could be the reason.

**Comment by jorgebastida** [comment]
I've just test #77 and as far as I can test it's a good solution. It's now on `develop` and I will release it soon as dajaxice 0.5.5

Thanks for the comments.
