### ISSUE TITLE
dajaxice.core.js breaks dojo/request using Dojo 1.8.3

### ISSUE THREAD

**Issue by ghost** [jorgebastida/django-dajaxice#87]
I could not get a simple usage of dojo/request (like the first example in http://dojotoolkit.org/documentation/tutorials/1.8/ajax/) to work while dajaxice.core.js was included in the page. Once I remove the {% dajaxice_js_import %} line dojo/request started working. I do not know how to debug this further.

**Comment by jorgebastida** [comment]
Probably related with #77 I'll release a fix soon as dajaxice 0.5.5

Thanks
