### ISSUE TITLE
Logging does not work anylonger

### ISSUE THREAD

**Issue by CPlusPlus17** [jorgebastida/django-dajaxice#88]
Updated today to the latest version of dajax and dajaxice.
Nearly nothing works since the update. I tried to debug it but 

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'logfile': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/portal/django.log'
        },
    },
    'loggers': {
        'dajaxice': {
            'handlers': ['logfile'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}

does not work any longer. The log file is just empty (it gets created but has no content).

**Comment by jorgebastida** [comment]
Any symptoms you can share?

**Comment by CPlusPlus17** [comment]
Nothing so far. Found the source of the problems I wanted to debug. Somehow I need to cast everything to string that it is working. 
But the logging still does nothing. 

I use django 1.4. Any way I can help with?

**Comment by CPlusPlus17** [comment]
Checked all commits >= 6 months ago.
I can't find any change that can cause this.

As soon as something is not working in dajaxice:
- InnerHTML does not get a string ()
- Missing import

"Something went wrong" is triggered but no log file at all is written. (Sending it per mail does not work too)
I'm out of ideas, maybe I do a commit-by-commit test to find the problem.

**Comment by CPlusPlus17** [comment]
Debugging got lost with 56f1d97b3cb1c90f784056ba4cf642f2b3fa40a5 cause of replacement of ./dajaxice/core/DajaxiceRequest.py.

Short verification:

56f1d97b3cb1c90f784056ba4cf642f2b3fa40a5
[root@dpweb django-dajaxice]# grep -R "log." .
.......
./dajaxice/core/Dajaxice.py:import logging
./dajaxice/core/Dajaxice.py:log = logging.getLogger('dajaxice')
./dajaxice/core/Dajaxice.py:            log.warning('%s already registered as dajaxice function.' % full_path)
./dajaxice/core/DajaxiceRequest.py:import logging
./dajaxice/core/DajaxiceRequest.py:log = logging.getLogger('dajaxice')
./dajaxice/core/DajaxiceRequest.py:            log.debug('Function %s is callable' % self.full_name)
./dajaxice/core/DajaxiceRequest.py:                    log.error('argv exception %s' % e)
./dajaxice/core/DajaxiceRequest.py:            log.debug('argv %s' % argv)
./dajaxice/core/DajaxiceRequest.py:                log.error(trace)
./dajaxice/core/DajaxiceRequest.py:            log.info('response: %s' % response)
./dajaxice/core/DajaxiceRequest.py:            log.debug('Function %s is not callable' % self.full_name)
......

1e31b967e6ea0d5acc84acd04cae4da004e8d861
[root@dpweb django-dajaxice]# grep -R "log." .
./dajaxice/core/Dajaxice.py:import logging
./dajaxice/core/Dajaxice.py:log = logging.getLogger('dajaxice')
./dajaxice/core/Dajaxice.py:            log.error('Ivalid function name %s.' % name)
./dajaxice/core/Dajaxice.py:            log.error('%s was already registered.' % name)
./dajaxice/templatetags/dajaxice_templatetags.py:import logging
./dajaxice/templatetags/dajaxice_templatetags.py:log = logging.getLogger('dajaxice')
./dajaxice/templatetags/dajaxice_templatetags.py:        log.warning("The 'request' object must be accesible within the "
./dajaxice/templates/dajaxice/dajaxice.core.js:    default_settings: {'default_exception_callback': function(){ console.log('Dajaxice: Something went wrong.')}}
./dajaxice/views.py:import logging
./dajaxice/views.py:log = logging.getLogger('dajaxice')

The complete trace code was never rewritten and is missing. This is the cause of it.

**Comment by CPlusPlus17** [comment]
This should improve the whole handling a lot, the ajax.py is never verified and so error detection was not possible.
With this debugging is possible again :)

Patch:

``` python
--- views.py    2013-02-02 00:26:28.332875288 +0100
+++ views.py.new    2013-02-02 00:26:48.900874615 +0100
@@ -1,4 +1,7 @@
 import logging
+import traceback
+import os
+import sys

 from django.conf import settings
 from django.utils import simplejson
@@ -50,11 +53,16 @@
             # Call the function. If something goes wrong, handle the Exception
             try:
                 response = function.call(request, **data)
-            except Exception:
+            except Exception, e:
+                trace = '\n'.join(traceback.format_exception(*sys.exc_info()))
+                log.error(trace)
+
                 if settings.DEBUG:
                     raise
+
                 response = dajaxice_config.DAJAXICE_EXCEPTION

             return HttpResponse(response, mimetype="application/x-json")
         else:
             raise FunctionNotCallableError(name)
+
```

Output:
Traceback (most recent call last):

  File "/var/portal/dajaxice/views.py", line 56, in dispatch
    response = function.call(request, **data)

  File "/var/portal/dajaxice/core/Dajaxice.py", line 21, in call
    return self.function(_args, *_kwargs)

  File "/var/portal/portal/customers/ajax.py", line 132, in ajax_login_load
    dajax.assign('#textpopuptext','innerHTML',render_to_response("userauth/static_htmls/login.html").content)

NameError: global name 'render_to_response' is not defined

**Comment by duduklein** [comment]
Any estimate on when this will be re-implemented?

**Comment by jorgebastida** [comment]
I'm pretty busy these days, I'll try to fix a couple of bugs soon but in the mean time... pull requests are welcome!

**Comment by dbrgn** [comment]
Would be great if this would get fixed, so that Sentry integration works. Logging is important.
