### ISSUE TITLE
Please remove zip_safe

### ISSUE THREAD

**Issue by angelabad** [jorgebastida/django-dajaxice#9]
Hi Jorge, please remove zip_safe from setup.py. Is an unrecognized option for standard python distutils.

Here is the patch included in debian package:

--- a/setup.py
+++ b/setup.py
@@ -13,7 +13,6 @@
     url = "http://dajaxproject.com",
     packages= ['dajaxice', 'dajaxice.templatetags', 'dajaxice.core', 'dajaxice.management.commands'],
     package_data = {'dajaxice': ['templates/dajaxice/*']},
-    zip_safe = False,
   classifiers=['Development Status :: 4 - Beta',
               'Environment :: Web Environment',
               'Framework :: Django',
  @@ -22,4 +21,4 @@
               'Operating System :: OS Independent',
               'Programming Language :: Python',
               'Topic :: Utilities']
  -)
  \ No newline at end of file
  +)

**Comment by angelabad** [comment]
http://svn.debian.org/viewsvn/python-modules/packages/dajaxice/trunk/debian/patches/remove_zip_safe_for_distutils?revision=12477&view=markup

**Comment by jorgebastida** [comment]
Fixed in http://github.com/jorgebastida/django-dajaxice/commit/335a7b06d5c08911b9cf40ad48ce2b777f0c38bb
